### ISSUE TITLE
Meta Bug: Adding Leap Blender 

### ISSUE THREAD

**Issue by arky** [gellweiler/leap-blender#1]
Please kindly add this leap-blender project as community contributed addon to blender. Please kindly file any dependency bugs to this meta bug. Thanks!

**Comment by gellweiler** [comment]
Sorry about the late answer. I didn't saw the message. This is unmaintained code, that was developed by me and a friend during a school internship, some years ago. We never tested it, since then. I don't have any intention of maintaining it and I therefore I won't upload it to a blender add-on store (does that even exist?) or some equivalent place.
I've now added a MIT-License tough. So anybody can do with it, whatever she/he wants.
